services:
  postgres:
    image: postgres:16-alpine
    container_name: hub-postgres
    environment:
      POSTGRES_DB: sistema_urbanape
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: host
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_urbanape"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    container_name: hub-auth-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sistema_urbanape
      DB_USERNAME: postgres
      DB_PASSWORD: host
      JWT_SECRET: UmaChaveMuitoSecretaParaOProjetoDeTransporte2026
      JWT_EXPIRATION: 7200000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
    container_name: hub-user-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sistema_urbanape
      DB_USERNAME: postgres
      DB_PASSWORD: host
      JWT_SECRET: UmaChaveMuitoSecretaParaOProjetoDeTransporte2026
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./card-manager-frontend
    container_name: hub-frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - user-service

volumes:
  postgres_data:
